#!/bin/sh
# shellcheck disable=SC2039

# help
if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    man autokiosk.1 || ronn -r <README.md | man -l -
    exit
fi

# must run as normal user
if [ "$(id -u)" = 0 ]; then
    echo 'This script must be run as a normal user, not root!' >&2
    exit 1
fi

LOG="$HOME/.autokiosk.log"
LOG_ERR="$HOME/.autokiosk_error.log"
rm -f "$LOG" "$LOG_ERR"

TARGET="$1"
ACTION="$2"

if [ "$TARGET" = "close-all" ]; then
    ACTION="$TARGET"
fi
if [ "$TARGET" = "hide-vms" ]; then
    ACTION="$TARGET"
fi
if [ "$TARGET" = "hide-all" ]; then
    ACTION="$TARGET"
fi

error() {
    echo "ERROR: $1" | tee -a "$LOG"
    exit 1
}

DATE=$(date)
echo "TARGET: $TARGET ACTION: $ACTION - $DATE" >>"$LOG"

# default display fallback
if [ -z "$DISPLAY" ]; then
    # required if run from terminal
    export DISPLAY=:0 1>>"$LOG" 2>>"$LOG_ERR"
    # required for systemd to run as service
    echo "Running autokiosk in none-interactive mode"
    xhost +local: 1>>"$LOG" 2>>"$LOG_ERR"
fi

# wait for an openbox session
if ! w | grep -qF openbox; then
    echo "no openbox session found"
fi

abort_if_running() {
    # shellcheck disable=SC2009
    RUNNING_INSTANCES=$(ps -eo args | grep -v grep |
        grep -F "$1" | grep -F "$2")
    if [ -n "$RUNNING_INSTANCES" ]; then
        echo "Already running: $1 $2"
        exit 1
    fi
}

open_http() {
    echo "Open URL $TARGET"

    # default kiosk application
    if command -v simple-kiosk 1>/dev/null; then
        abort_if_running simple-kiosk "$TARGET"
        nohup simple-kiosk "$TARGET" >/dev/null 2>&1 &
    # Chromium fallback
    # only use as last resort,
    # Chromium can be unstable on ARM and has hardcoded keyboard controls
    elif command -v chromium 1>/dev/null; then
        # find desktop resolution of first monitor
        # shellcheck disable=SC2063
        RES=$(xrandr | grep '*' | head -n1 | awk '{print $1}' | tr 'x' ',')
        if [ -z "$RES" ]; then
            error "Failed to find desktop resolution"
        fi
        abort_if_running chromium "$TARGET"
        nohup chromium "$TARGET" \
            --window-size="$RES" \
            --start-fullscreen \
            --kiosk \
            --incognito \
            --noerrdialogs \
            --disable-translate \
            --no-first-run \
            --fast \
            --fast-start \
            --disable-infobars \
            --disable-features=TranslateUI \
            --disk-cache-dir=/dev/null \
            --password-store=basic >/dev/null 2>&1 &
    else
        error "Failed to find simple-kiosk or chromium"
    fi
}

open_vm() {
    echo "Open VM $TARGET"

    if [ -z "$(command -v virt-viewer)" ]; then
        error "Failed to find virt-viewer"
    fi

    # set default URI
    if [ -z "$LIBVIRT_DEFAULT_URI" ]; then
        export LIBVIRT_DEFAULT_URI="qemu:///system"
    fi

    # verify
    if [ -z "$LIBVIRT_DEFAULT_URI" ]; then
        error "LIBVIRT_DEFAULT_URI is unset"
    fi
    if [ -z "$DISPLAY" ]; then
        error "DISPLAY is unset"
    fi

    # shellcheck disable=SC2129
    echo "LIBVIRT_DEFAULT_URI $LIBVIRT_DEFAULT_URI" >>"$LOG"
    echo "DISPLAY $DISPLAY" >>"$LOG"
    echo "HOME $HOME" >>"$LOG"

    # open VM in fullscreen
    abort_if_running virt-viewer "$TARGET"
    nohup virt-viewer -v "$TARGET" --reconnect --wait --kiosk \
        1>>"$LOG" 2>>"$LOG_ERR" &
#    nohup sleep 2 && xdotool search --name "$TARGET" set_window \
#        --name "$TARGET" 1>>"$LOG" 2>>"$LOG_ERR" &
#    nohup sleep 6 && xdotool search --name "$TARGET" set_window \
#        --name "$TARGET" 1>>"$LOG" 2>>"$LOG_ERR" &
}

pid_to_ident() {
    local WINDOWS
    local LINE
    local CURRENT_WINDOW_ID
    local CURRENT_WINDOW_PID

    # convert PID to wmctrl window identifier
    PID="$1"

    # get a list of all windows
    WINDOWS=$(mktemp)
    wmctrl -p -l 2>/dev/null >"$WINDOWS"

    while IFS="" read -r i || [ -n "$i" ]; do
        LINE=$(printf '%s\n' "$i")
        CURRENT_WINDOW_ID=$(echo "$LINE" | awk '{print $1}')
        CURRENT_WINDOW_PID=$(echo "$LINE" | awk '{print $3}')
        # if the window exists
        if [ "$CURRENT_WINDOW_PID" = "$PID" ]; then
            echo "$CURRENT_WINDOW_ID"
        fi
    done <"$WINDOWS"

    rm -f "$WINDOWS"
}

hide_process() {
    local PROCESS_ID
    local CMD_LINE
    local WINDOW_ID
    local i
    local STR_A
    local STR_B
    STR_A="$1"
    STR_B="$2"
    if [ -z "$STR_A" ]; then
        error "hide_process: STR_A is unset"
    fi
    if [ -z "$STR_B" ]; then
        STR_B="$STR_A"
    fi

#    if [ "$STR_A" = "virt-viewer" ]; then
#        xdotool search --name "$TARGET" set_window --name "$TARGET" \
#            1>>"$LOG" 2>>"$LOG_ERR"
#    fi

    # shellcheck disable=SC2009
    PROCESS_ID=$(ps ax | grep -v grep | grep -iF "$STR_A" |
        grep -iF "$STR_B" | sed '/^ *$/d' | awk '{print $1}')
    if [ -n "$PROCESS_ID" ]; then
        for i in $PROCESS_ID; do
            CMD_LINE=$(ps -p "$i" -o args --no-headers)
            # find current window identifier
            WINDOW_ID=$(pid_to_ident "$i" | head -n1)
            # hide window by identifier
            if [ -n "$WINDOW_ID" ]; then
                echo "Hide window: $CMD_LINE" | tee -a "$LOG"
                wmctrl -i -r "$WINDOW_ID" -b add,hidden ||
                    error "Hide window: ID:$WINDOW_ID CMD:$CMD_LINE"
            fi
        done
    fi
}

close_process() {
    local PROCESS_ID
    local CMD_LINE
    local i
    local STR_A
    local STR_B
    STR_A="$1"
    STR_B="$2"
    if [ -z "$STR_A" ]; then
        error "close_process: STR_A is unset"
    fi
    if [ -z "$STR_B" ]; then
        STR_B="$STR_A"
    fi

    # shellcheck disable=SC2009
    PROCESS_ID=$(ps ax | grep -v grep | grep -iF "$STR_A" |
        grep -iF "$STR_B" | sed '/^ *$/d' | awk '{print $1}')
    if [ -n "$PROCESS_ID" ]; then
        for i in $PROCESS_ID; do
            CMD_LINE=$(ps -p "$i" -o args --no-headers)
            echo "Kill process: $CMD_LINE" | tee -a "$LOG"
            kill "$i" 2>/dev/null
        done
    fi
}

case $ACTION in
close-all)
    close_process simple-kiosk http
    close_process chromium
    close_process virt-viewer
    exit 0
    ;;
close)
    echo "Stop $TARGET"
    if echo "$TARGET" | grep -q '^http'; then
        if command -v simple-kiosk 1>/dev/null; then
            close_process simple-kiosk "$TARGET"
        else
            close_process chromium "$TARGET"
        fi
    else
        close_process virt-viewer "$TARGET"
    fi
    ;;
hide)
    echo "Hide $TARGET"
    if echo "$TARGET" | grep -q '^http'; then
        if command -v simple-kiosk 1>/dev/null; then
            hide_process simple-kiosk "$TARGET"
        else
            hide_process chromium "$TARGET"
        fi
    else
        hide_process virt-viewer "$TARGET"
    fi
    ;;
hide-vms)
    hide_process virt-viewer
    ;;
hide-all)
    hide_process virt-viewer
    hide_process simple-kiosk
    hide_process chromium
    ;;
*)
    # open target
    if echo "$TARGET" | grep -q '^http'; then
        open_http
    else
        open_vm
    fi
    ;;
esac
