#!/bin/sh
#info: Configure openbox for kiosk mode, autologin user

set -e

error() {
    echo "Error: $1" >&2
    exit 1
}

# must run as root
[ "$(id -u)" -ne 0 ] && error 'This script must be run as root!'

TARGET_USER="$1"
[ -z "$TARGET_USER" ] && error "Missing variable TARGET_USER"

# variables
DIR_CFG="/etc/xdg/openbox"
AUTOSTART="$DIR_CFG/autostart"
AUTOSTART_KIOSK="/usr/share/autokiosk/openbox-autostart"
RC="$DIR_CFG/rc.xml"
RC_KIOSK="/usr/share/autokiosk/openbox-rc.xml"
TINT_THEME="/usr/share/autokiosk/tint2rc"
TINT_THEME_KISOK="/etc/xdg/tint2/tint2rc"

# verify openbox
[ -d "$DIR_CFG" ] || error "openbox does not seem to be installed"

# custom autostart file
cp -f "$AUTOSTART_KIOSK" "$AUTOSTART"
chmod 755 "$AUTOSTART"

# custom desktop settings
cp -f "$RC_KIOSK" "$RC"
chmod 644 "$RC"

# custom tint2 panel theme
cp -f "$TINT_THEME" "$TINT_THEME_KISOK"
chmod 644 "$TINT_THEME_KISOK"

# autologin current user
CFG_LIGHTDM="/etc/lightdm/lightdm.conf"
if ! [ -f "$CFG_LIGHTDM" ]; then
    error "lightdm does not seem to be installed"
fi
# autologin user
sed -i "/autologin-user=/c\autologin-user=$TARGET_USER" "$CFG_LIGHTDM" ||
    error "Failed to set autologin user"
sed -i "/autologin-user-timeout=/c\autologin-user-timeout=0" "$CFG_LIGHTDM" ||
    error "Failed to set autologin timeout"

echo "please restart lightdm"
